services:

  app: # アプリケーション
    build: ./docker/app
    volumes: # アプリケーションコードをバインドマウント
      - type: bind
        source: ./docker/app
        target: /app

  web: # Webサーバー
    image: nginx:stable
    ports:
      - "8080:80"
    volumes: # Nginxの設定ファイルをバインドマウント
      - type: bind
        source: ./docker/web/nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./frontend
        target: /usr/share/nginx/html
    depends_on: # アプリケーションコンテナに依存
      - app