server {
    # 80番ポートでリクエストを受ける
    listen 80;

    # サーバー名をlocalhostに設定
    server_name localhost;

    # フロントエンドのファイルを表示するためのルートディレクトリを指定
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # pythonのAPIへのリクエストをappコンテナに転送する設定
    location /api/ {
        proxy_pass http://app:8000/;  # appコンテナの8000番ポートにリクエストを転送
        proxy_set_header Host $host;
    }
}